const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.find,
		C3.Plugins.LocalStorage.Cnds.OnItemSet,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.Es_ui_Event1_Act1,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{bg_quintal: 0},
	{bg_servico: 0},
	{bg_escola: 0},
	{bg_mapa: 0},
	{CaseID: 0},
	{Kind: 0},
	{Index: 0},
	{Art: 0},
	{Done: 0},
	{CaseSprite: 0},
	{InspectSprite: 0},
	{Lia: 0},
	{Action: 0},
	{Scope: 0},
	{Order: 0},
	{Enabled: 0},
	{UIKey: 0},
	{UIButton: 0},
	{Panel: 0},
	{DarkPanel: 0},
	{Scrim: 0},
	{Focus: 0},
	{Key: 0},
	{Label: 0},
	{ModalTitle: 0},
	{ModalBody: 0},
	{Choice1: 0},
	{Choice2: 0},
	{Toast: 0},
	{Marker: 0},
	{Touch: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{UIButtonFocus: 0},
	{UIButtonPressed: 0},
	{UIButtonDisabled: 0},
	{g_ready: 0},
	{g_boot: 0},
	{g_pending: 0},
	{g_save_ok: 0},
	{g_save_busy: 0},
	{g_save_dirty: 0},
	{g_has_save: 0},
	{g_phase: 0},
	{g_scene: 0},
	{g_win1: 0},
	{g_win2: 0},
	{g_win3: 0},
	{g_care: 0},
	{g_safe: 0},
	{g_correct: 0},
	{g_kind: 0},
	{g_key_focus: 0},
	{g_choice: 0},
	{g_errors: 0},
	{g_hint_step: 0},
	{g_focus: 0},
	{g_focus_max: 0},
	{g_ignore_until: 0},
	{g_reduced: 0},
	{g_sfx: 0},
	{g_music: 0},
	{g_audio_started: 0},
	{g_committed: 0},
	{g_action_deadline: 0},
	{g_return_settings: 0},
	{g_done: 0},
	{g_scope: 0},
	{g_mode: 0},
	{g_action: 0},
	{g_key_scope: 0},
	{g_case: 0},
	{g_art: 0},
	{g_title: 0},
	{g_body: 0},
	{g_opt1: 0},
	{g_opt2: 0},
	{g_success: 0},
	{g_wrong: 0},
	{g_save_message: 0},
	{g_payload: 0},
	{g_confirm_return: 0},
	{g_hint_target: 0},
	{g_escape_mode: 0},
	{g_dispatch: 0},
	{g_was_saved: 0},
	{g_was_complete: 0},
	{g_hint_soft: 0},
	{g_hint_label: 0},
	{g_hint_index: 0},
	{g_ui_block_until: 0}
];

self.InstanceType = {
	bg_quintal: class extends self.ISpriteInstance {},
	bg_servico: class extends self.ISpriteInstance {},
	bg_escola: class extends self.ISpriteInstance {},
	bg_mapa: class extends self.ISpriteInstance {},
	CaseSprite: class extends self.ISpriteInstance {},
	InspectSprite: class extends self.ISpriteInstance {},
	Lia: class extends self.ISpriteInstance {},
	UIButton: class extends self.I9PatchInstance {},
	Panel: class extends self.I9PatchInstance {},
	DarkPanel: class extends self.I9PatchInstance {},
	Scrim: class extends self.I9PatchInstance {},
	Focus: class extends self.I9PatchInstance {},
	Label: class extends self.ITextInstance {},
	ModalTitle: class extends self.ITextInstance {},
	ModalBody: class extends self.ITextInstance {},
	Choice1: class extends self.ITextInstance {},
	Choice2: class extends self.ITextInstance {},
	Toast: class extends self.ITextInstance {},
	Marker: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	UIButtonFocus: class extends self.I9PatchInstance {},
	UIButtonPressed: class extends self.I9PatchInstance {},
	UIButtonDisabled: class extends self.I9PatchInstance {}
}